"""What may be done to a link, and what may be *called* a repair.

The audit's F-010, rewritten after the owner and a second reviewer both said the
first answer was wrong. It is worth writing the whole reasoning down, because
the shape of the mistake is one this program can make again in ten other places.

A reference like::

    <a href="przypisy.xhtml#fn-17" epub:type="noteref">17</a>

is two claims at once: *this file* and *this place inside it*. When the file is
there and the anchor is not, EPUBCheck says so, and the cheap way to make it
stop saying so is to drop the fragment. The link then validates. It also lands
the reader at the top of the notes — footnote one — while the marker in the text
still says seventeen. Nobody can see that. The validator is quiet, the report
said "repaired", and the book is wrong in a way it was not wrong before.

So this module exists to make one distinction impossible to blur:

    validator silence != semantic repair

Three states, and only three:

``PRESERVED``
    The target exists, the anchor exists. Nothing to do.

``REPAIRED``
    The reference changed, and the program can *show* why the new target means
    what the old one meant: the file was moved by this rebuild and the path map
    says where to, an id was renamed by this rebuild and the rename map says
    what to, or a document was regenerated by this rebuild under a mapping it
    wrote itself (``spis`` → ``toc``). Every one of those is a fact about a
    transformation this program performed. None of them is a guess.

``UNRESOLVED``
    Everything else. The target document has no such anchor and nothing here
    knows where it was meant to lead.

An ``UNRESOLVED`` reference is never quietly rewritten. In `preserve` it is kept
exactly as the publisher wrote it and reported as a defect inherited from the
source — not as something this tool fixed. In `strict` the build stops: strict
is chosen by somebody who wants a file that conforms, and a book with references
this program cannot honestly resolve is not one, so it says so instead of
manufacturing conformance.

**And then there is the third option, which is the owner's.** A program that
cannot decide something has a choice between guessing and asking, and this one
had only ever been allowed to guess — because asking costs autonomy, and
autonomy had quietly become the thing being optimised. It is not the thing being
optimised. `Resolver` is how a front end offers the question to the person
holding the book: here is the link, here is what its text says, here are the
anchors the target document actually has. A human answer is evidence the program
does not have, and a reference resolved that way is genuinely repaired — by
somebody who could look.

No resolver means no question, which is what a batch run and the corpus want.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Protocol


class Resolution(str, Enum):
    """What happened to one reference, in the only three words allowed."""

    #: Target and anchor both exist; the reference was not touched.
    PRESERVED = "preserved"
    #: Rewritten under a mapping this rebuild produced and can point at.
    REPAIRED = "repaired"
    #: The anchor is not there and nothing here knows where it belonged.
    UNRESOLVED = "unresolved"


@dataclass(frozen=True)
class Unresolved:
    """One reference this program cannot honestly resolve.

    Carries what a person would need to answer the question, and what a report
    needs to state it: where the link is, where it points, what it says on the
    page, and which anchors the target document does have.
    """

    #: Container path of the document holding the link.
    document: str
    #: Container path of the document it points at, as the output will hold it.
    target: str
    #: The anchor named after the `#`, without it.
    fragment: str
    #: The link's own text — usually the footnote number, which is the single
    #: most useful thing a person can be shown when asked where it belongs.
    text: str = ""
    #: Ids the target document actually has, in document order.
    candidates: tuple[str, ...] = ()

    @property
    def reference(self) -> str:
        return f"{self.target}#{self.fragment}"

    def __str__(self) -> str:
        return f"{self.document} -> {self.reference}"


#: A person said: leave it exactly as the publisher wrote it.
KEEP = "keep"
#: A person named an anchor in the target document.
REPOINT = "repoint"
#: A person said: this link should lead to the document, not into it. The one
#: legitimate route from a dead fragment to no fragment, and it goes through a
#: human being who looked at the book.
POINT_AT_DOCUMENT = "point-at-document"


@dataclass(frozen=True)
class Decision:
    """A person's answer to one `Unresolved`."""

    action: str = KEEP
    #: The anchor chosen, when `action` is `REPOINT`.
    fragment: str = ""
    #: Apply this answer to every remaining unresolved reference in this book.
    #: A conversion can leave two hundred of these, and being asked two hundred
    #: times is how a feature becomes something people switch off.
    apply_to_all: bool = False

    def __post_init__(self) -> None:
        if self.action not in (KEEP, REPOINT, POINT_AT_DOCUMENT):
            raise ValueError(f"unknown decision: {self.action!r}")
        if self.action == REPOINT and not self.fragment:
            raise ValueError("repointing needs somewhere to point")


class Resolver(Protocol):
    """A front end that can ask a person what a broken reference meant.

    Implemented by the window; not implemented by anything that runs unattended.
    A resolver may return `None`, which means the same as `Decision()`: leave it
    alone. It must not raise — a front end that cannot answer has not answered,
    and the rebuild carries on with the reference untouched.
    """

    def resolve(self, question: Unresolved) -> Decision | None:  # pragma: no cover
        ...


@dataclass
class Answers:
    """The decisions made during one rebuild, and the standing ones.

    `apply_to_all` is remembered here rather than in the stage, because the
    stage runs once per document and the promise is per book.
    """

    standing: Decision | None = None
    given: list[tuple[Unresolved, Decision]] = field(default_factory=list)

    def ask(self, resolver: Resolver | None, question: Unresolved) -> Decision:
        if self.standing is not None:
            return self.standing
        if resolver is None:
            return Decision()
        try:
            answer = resolver.resolve(question) or Decision()
        except Exception:  # noqa: BLE001 — a front end that failed has not answered
            return Decision()
        if answer.apply_to_all:
            # Standing answers only carry when they mean the same thing
            # everywhere. "Point this one at anchor `fn-3`" does not.
            if answer.action != REPOINT:
                self.standing = answer
        self.given.append((question, answer))
        return answer


__all__ = [
    "Answers",
    "Decision",
    "KEEP",
    "POINT_AT_DOCUMENT",
    "REPOINT",
    "Resolution",
    "Resolver",
    "Unresolved",
]
