"""Every identifier a book declares comes out, with the scheme it came in with.

WP-9, EF-025 and EF-035. Three defects in one stretch of the writer, and they
only show up together once a book carries **more than one** identifier — which
is why the suite had not seen them. A book with a single `dc:identifier` is the
common case and the one every fixture had.

* `identifier-type` was written only for the primary identifier. An ISBN
  declared as `opf:scheme="ISBN"` came out as a bare `dc:identifier`: the
  number survived, the statement *that it is an ISBN* did not.
* The identifiers were numbered twice, over different sets. The elements were
  numbered over the **non-primary** ones and the id map over **all** of them,
  so with three identifiers the third element is written `id-1` while every
  refinement pointing at it says `id-2`. A refinement whose target does not
  exist is not a preserved statement, it is an invalid one — which is F-011's
  own sentence, and this is the same defect one level down.
* `file-as` and `role` are generated by the writer when the source did not have
  them. That is a value appearing in the output that was never in the input,
  and until now it appeared with nothing in the change ledger saying so.

The fixture here carries three identifiers on purpose: a UUID as the primary
one, an ISBN with a scheme, and a vendor identifier with a refinement the model
has no field for. All three of those are ordinary — the third is what a shop
writes — and any book that has them exercises all three defects at once.
"""

from __future__ import annotations

import re
import zipfile

import pytest

from epubforge.pipeline import rebuild
from epubforge.policy import Policy
from epubforge.report import Action
from epubforge.validate import find_epubcheck, validate
from epubforge.report import Report
from tests.factory import CONTAINER, MODERN_NAV

needs_epubcheck = pytest.mark.skipif(
    find_epubcheck() is None, reason="EPUBCheck nie jest tu zainstalowany"
)

PACKAGE = """<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://www.idpf.org/2007/opf" version="3.0" unique-identifier="pub-id"
         xmlns:opf="http://www.idpf.org/2007/opf">
  <metadata xmlns:dc="http://purl.org/dc/elements/1.1/">
    <dc:identifier id="pub-id">urn:uuid:11111111-2222-3333-4444-555555555555</dc:identifier>
    <meta refines="#pub-id" property="identifier-type" scheme="xsd:string">UUID</meta>
    <dc:identifier id="isbn">9788324631766</dc:identifier>
    <meta refines="#isbn" property="identifier-type" scheme="onix:codelist5">15</meta>
    <dc:identifier id="sklep">x-custom:ZAM-2026-0001</dc:identifier>
    <meta refines="#sklep" property="display-seq">3</meta>
    <dc:title>Książka o trzech identyfikatorach</dc:title>
    <dc:language>pl</dc:language>
    <dc:creator id="autor">Imię Nazwisko</dc:creator>
    <meta property="dcterms:modified">2020-01-01T00:00:00Z</meta>
  </metadata>
  <manifest>
    <item id="nav" href="nav.xhtml" media-type="application/xhtml+xml" properties="nav"/>
    <item id="ch1" href="chapter.xhtml" media-type="application/xhtml+xml"/>
  </manifest>
  <spine><itemref idref="ch1"/></spine>
</package>
"""

CHAPTER = """<?xml version="1.0" encoding="utf-8"?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pl">
<head><meta charset="utf-8"/><title>Rozdział</title></head>
<body><h1>Rozdział</h1><p>Zdanie, które musi przetrwać przebudowę.</p></body>
</html>
"""


@pytest.fixture
def three_identifiers(tmp_path) -> str:
    path = str(tmp_path / "trzy.epub")
    with zipfile.ZipFile(path, "w") as archive:
        info = zipfile.ZipInfo("mimetype")
        info.compress_type = zipfile.ZIP_STORED
        archive.writestr(info, "application/epub+zip")
        archive.writestr("META-INF/container.xml", CONTAINER)
        archive.writestr("OEBPS/content.opf", PACKAGE)
        archive.writestr("OEBPS/nav.xhtml", MODERN_NAV)
        archive.writestr("OEBPS/chapter.xhtml", CHAPTER)
    return path


def package_of(result) -> str:
    with zipfile.ZipFile(result.output_path) as archive:
        name = next(entry for entry in archive.namelist() if entry.endswith(".opf"))
        return archive.read(name).decode()


@pytest.fixture
def written(three_identifiers, tmp_path):
    result = rebuild(
        three_identifiers,
        str(tmp_path / "out.epub"),
        Policy.preset("preserve", validate_before_publish="off"),
    )
    assert result.status.wrote_a_file, result.report.to_text()
    return result


class TestNoIdentifierIsLost:
    def test_all_three_values_come_out(self, written):
        package = package_of(written)
        for value in (
            "urn:uuid:11111111-2222-3333-4444-555555555555",
            "9788324631766",
            "x-custom:ZAM-2026-0001",
        ):
            assert value in package, value

    def test_the_isbn_keeps_its_scheme(self, written):
        """EF-025's first third. The number survived before this; the statement
        that it *is an ISBN* did not, because `identifier-type` was written
        only for the primary identifier."""
        package = package_of(written)
        isbn_id = re.search(r'<dc:identifier id="([^"]+)">9788324631766<', package)
        assert isbn_id, package
        assert re.search(
            rf'<meta refines="#{re.escape(isbn_id.group(1))}" property="identifier-type"',
            package,
        ), package

    def test_the_primary_keeps_its_scheme_too(self, written):
        package = package_of(written)
        assert 'refines="#pub-id" property="identifier-type"' in package


class TestEveryRefinementPointsAtSomethingThatExists:
    """EF-025's second third, and the one that produces an invalid book rather
    than a poorer one.

    The elements were numbered over the non-primary identifiers and the id map
    over all of them. With three identifiers that is `id-1` written and `id-2`
    refined — a refinement aimed at nothing.
    """

    def test_no_refinement_names_a_missing_id(self, written):
        package = package_of(written)
        declared = set(re.findall(r'\bid="([^"]+)"', package))
        refined = set(re.findall(r'refines="#([^"]+)"', package))
        missing = sorted(refined - declared)
        assert not missing, f"refinements pointing at nothing: {missing}\n{package}"

    def test_the_carried_refinement_still_refines_the_right_identifier(self, written):
        """`display-seq` on the vendor identifier: the model has no field for
        it, so it is carried verbatim and re-pointed at whatever id the writer
        gave that node. Carried and mis-aimed would be worse than dropped."""
        package = package_of(written)
        vendor = re.search(r'<dc:identifier id="([^"]+)">x-custom:ZAM-2026-0001<', package)
        assert vendor, package
        assert re.search(
            rf'<meta refines="#{re.escape(vendor.group(1))}" property="display-seq"',
            package,
        ), package

    @needs_epubcheck
    def test_and_epubcheck_agrees(self, written):
        verdict = validate(written.output_path, Report(source=written.output_path))
        rsc = [message for message in verdict.messages if "RSC-" in message]
        assert not rsc, rsc


class TestWhatTheWriterInventsIsWrittenDown:
    """EF-035. `file-as` and `role` are generated when the source has neither.

    A value that appears in the output and was never in the input is exactly
    what the change ledger is for — and reguła S-02 says it plainly: whatever
    this program adds or removes has to be visible. Reported as `ADDED` rather
    than silently, so somebody comparing two packages can tell what the book
    said from what this program said about the book.
    """

    def test_a_generated_file_as_is_in_the_ledger(self, written):
        generated = [
            change for change in written.report.changes
            if change.rule == "metadata.file-as-generated"
        ]
        assert generated, [change.rule for change in written.report.changes]
        assert generated[0].action is Action.ADDED

    def test_a_generated_role_is_in_the_ledger(self, written):
        generated = [
            change for change in written.report.changes
            if change.rule == "metadata.role-generated"
        ]
        assert generated, [change.rule for change in written.report.changes]
        assert generated[0].action is Action.ADDED

    def test_what_the_source_declared_is_not_reported_as_generated(self, tmp_path):
        """The other half. A book that states `file-as` itself has nothing
        generated, and saying otherwise would be the same defect facing the
        other way: a ledger that cries wolf."""
        path = str(tmp_path / "wlasne.epub")
        package = PACKAGE.replace(
            '<dc:creator id="autor">Imię Nazwisko</dc:creator>',
            '<dc:creator id="autor">Imię Nazwisko</dc:creator>'
            '<meta refines="#autor" property="file-as">Nazwisko, Imię</meta>'
            '<meta refines="#autor" property="role" scheme="marc:relators">aut</meta>',
        )
        with zipfile.ZipFile(path, "w") as archive:
            info = zipfile.ZipInfo("mimetype")
            info.compress_type = zipfile.ZIP_STORED
            archive.writestr(info, "application/epub+zip")
            archive.writestr("META-INF/container.xml", CONTAINER)
            archive.writestr("OEBPS/content.opf", package)
            archive.writestr("OEBPS/nav.xhtml", MODERN_NAV)
            archive.writestr("OEBPS/chapter.xhtml", CHAPTER)

        result = rebuild(
            path, str(tmp_path / "wlasne-out.epub"),
            Policy.preset("preserve", validate_before_publish="off"),
        )
        rules = {change.rule for change in result.report.changes}
        assert "metadata.file-as-generated" not in rules
        assert "metadata.role-generated" not in rules
