"""The package document is well formed whatever the book carries.

WP-18, and the finding it came from turned out to be half right in a way worth
recording. EF-038 said the package document is assembled by concatenating
strings — 58 × `lines.append` — and treated the method as the risk.

The method is not the risk. Every value goes through `escape` or `quoteattr`,
and the hostile inputs below all come out as well-formed XML: `<script>`,
`]]>`, a bare XML declaration, a doubled hyphen where an XML comment cannot
carry one, five thousand characters, emoji outside the BMP.

What *did* come out broken was a control character, because there is nothing to
escape it to — XML 1.0 has no representation for it at all. Measured on the
default preset before the fix: a book whose title carried `0x0B` was **written**,
and its package document did not parse. An unopenable book, produced by the mode
people actually use, reported as a success.

And the repair EF-038 asked for would not have found it. Building a tree makes
lxml raise on those characters rather than write them, which moves the outcome
from an unopenable book to a crash — better, and still not a book.
"""

from __future__ import annotations

import zipfile

import pytest
from lxml import etree

from epubforge import writer
from epubforge.pipeline import rebuild
from epubforge.policy import Policy

from .test_dead_css_urls import book, rules_of

#: Every one of these was tried against the writer. The first eight already
#: worked and are kept so that a future change cannot quietly stop escaping;
#: the last three are the ones that produced a broken document.
HOSTILE = [
    "Tytuł <script>alert(1)</script>",
    "Tytuł & Spółka",
    'Tytuł "w cudzysłowie"',
    "Tytuł 'apostrof'",
    "Tytuł ]]> koniec",
    "Tytuł -- podwójny myślnik",
    "Tytuł z <![CDATA[ czymś ]]>",
    '<?xml version="1.0"?>',
    "Tytuł \U0001f600 emoji",
    "A" * 5000,
    "Tytuł\nz\nnowymi\nliniami",
    "Tytuł z pionową tabulacją \x0b i dzwonkiem \x07",
    "Tytuł z bajtem zerowym \x00",
    "Tytuł z \x1f jednostkowym separatorem",
]


def written(tmp_path, title: str, preset: str = "preserve"):
    policy = Policy.preset(preset)
    policy.render_gate = "off"
    policy.metadata_overrides["title"] = title
    policy.metadata_overrides["author"] = title
    source = book(tmp_path / "in.epub", "p { margin: 0 }")
    return rebuild(source, str(tmp_path / "out.epub"), policy)


def package_of(result) -> bytes:
    with zipfile.ZipFile(result.output_path) as archive:
        return archive.read(next(n for n in archive.namelist() if n.endswith(".opf")))


class TestWhateverTheTitleSaysThePackageParses:
    @pytest.mark.parametrize("title", HOSTILE)
    def test_the_package_document_is_well_formed(self, tmp_path, title):
        result = written(tmp_path, title)
        assert result.output_path, result.report.to_text()
        etree.fromstring(package_of(result))  # raises if it is not

    @pytest.mark.parametrize("title", HOSTILE)
    def test_and_nothing_raises_on_the_way(self, tmp_path, title):
        """A crash instead of a broken file is not the fix — it is the other
        failure. The book comes out either way."""
        assert written(tmp_path, title).output_path


class TestEveryGeneratedFileAndNotOnlyThePackage:
    """The defect was wider than the package document, and this is how it was
    found: fixing `writer` left `nav.xhtml` and `toc.ncx` broken, because those
    are generated by the navigation stage from the same metadata through a
    different escaping helper. Both were written, both unopenable, and the run
    reported `succeeded`.

    So the assertion is over *everything the rebuild produces*, rather than over
    the file the finding happened to name.
    """

    @pytest.mark.parametrize("title", ["Tytuł \x0b z kontrolnym", "Tytuł \x00 zero"])
    def test_nothing_in_the_archive_fails_to_parse(self, tmp_path, title):
        result = written(tmp_path, title)
        assert result.output_path, result.report.to_text()
        with zipfile.ZipFile(result.output_path) as archive:
            for name in archive.namelist():
                if name.endswith((".xhtml", ".opf", ".ncx")):
                    etree.fromstring(archive.read(name))  # raises if it is not

    def test_the_navigation_document_keeps_the_rest_of_the_title(self, tmp_path):
        result = written(tmp_path, "Wiedźmin \x0b Ostatnie życzenie")
        with zipfile.ZipFile(result.output_path) as archive:
            nav = archive.read(
                next(n for n in archive.namelist() if n.endswith("nav.xhtml"))
            ).decode("utf-8")
        assert "Wiedźmin" in nav and "Ostatnie życzenie" in nav


class TestOnlyTheImpossibleCharactersGo:
    def test_the_rest_of_the_title_survives(self, tmp_path):
        """The removal is surgical. A title that loses its control character and
        its words is a title this program invented."""
        result = written(tmp_path, "Wiedźmin \x0b Ostatnie życzenie")
        package = package_of(result).decode("utf-8")
        assert "Wiedźmin" in package and "Ostatnie życzenie" in package

    def test_ordinary_punctuation_is_untouched(self, tmp_path):
        result = written(tmp_path, "Tytuł — „w cudzysłowie” & Spółka")
        parsed = etree.fromstring(package_of(result))
        titles = parsed.findall(".//{http://purl.org/dc/elements/1.1/}title")
        assert any("Spółka" in (t.text or "") for t in titles)
        assert any("„w cudzysłowie”" in (t.text or "") for t in titles)

    @pytest.mark.parametrize("keep", ["\t", "\n", "\r"])
    def test_tab_newline_and_carriage_return_are_legal_and_stay(self, keep):
        """The three control characters XML does allow. Removing them would be
        the same mistake in the other direction."""
        assert writer.forbidden_characters(f"a{keep}b") == 0

    @pytest.mark.parametrize("drop", ["\x00", "\x07", "\x0b", "\x0c", "\x1f"])
    def test_and_the_ones_it_does_not_are_counted(self, drop):
        assert writer.forbidden_characters(f"a{drop}b") == 1


class TestItIsNeverSilent:
    """S-02's spirit: the program is editing somebody's title, so it says so."""

    def test_the_report_names_the_field(self, tmp_path):
        result = written(tmp_path, "Tytuł \x0b z kontrolnym")
        said = next(
            f
            for f in result.report.findings
            if f.rule == "package.forbidden-characters-removed"
        )
        assert "title" in said.values["fields"]

    def test_a_clean_book_says_nothing(self, tmp_path):
        result = written(tmp_path, "Zwyczajny tytuł")
        assert "package.forbidden-characters-removed" not in rules_of(result)


class TestTheEscapingItselfStillHappens:
    """Guarding the shadowed helpers. They are the reason fifty-seven call sites
    did not have to be edited, and a mistake in them would be a mistake
    everywhere at once."""

    def test_markup_in_text_is_escaped(self):
        assert writer.escape("<b>&</b>") == "&lt;b&gt;&amp;&lt;/b&gt;"

    def test_quotes_in_attributes_are_escaped(self):
        assert writer.quoteattr('a"b') in ('\'a"b\'', '"a&quot;b"')

    def test_and_both_drop_what_xml_cannot_carry(self):
        assert "\x0b" not in writer.escape("a\x0bb")
        assert "\x0b" not in writer.quoteattr("a\x0bb")
